---
name: Build
on:  # yamllint disable-line rule:truthy
  push:
    paths-ignore:
      - 'README.md'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install ubuntu-image
        run: sudo snap install ubuntu-image --classic
      - name: Build images
        run: ./scripts/build-images.sh
