---
name: Build
on: push  # yamllint disable-line rule:truthy
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install ubuntu-image
        run: snap install ubuntu-image --classic
      - name: Build images
        run: ./scripts/build-images.sh
